spring:
  datasource:
    url: jdbc:h2:mem:paging-db
    username: sa
    password:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          sharedcache:
            mode: ENABLE_SELECTIVE

    generate-ddl: true
    hibernate:
      ddl-auto: create